---
- name: Create user deployer
  become: true
  user: name=deployer append=yes state=present createhome=yes

- name: Add sudoers deployer
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^deployer'
    line: 'deployer ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: deploy ssh key
  become: true
  authorized_key: user=deployer state=present key={{ item }}
  with_file:
    - ansible_rsa.pub

- name: change root user into aliases
  become: true
  lineinfile:
    path: /etc/aliases
    regexp: "^root:"
    line: "root: root"

- name: fake mail
  become: true
  shell: "echo 'test' | mail root"

- name: ln /var/mail/root
  become: true
  file: src=/var/mail/mail dest=/var/mail/root state=link
